"""Add rule tables

Revision ID: add_rule_tables
Revises: 3ad8753e53e6
Create Date: 2024-03-07 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_rule_tables'
down_revision = '3ad8753e53e6'  # 这里指向之前的迁移
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('regulator_address', sa.String(length=42), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('contract_address', sa.String(length=42), nullable=False),
        sa.Column('owner', sa.String(length=100), nullable=False),
        sa.Column('rule_id', sa.String(length=20), nullable=False),
        sa.Column('status', sa.Integer(), nullable=True),
        sa.Column('create_time', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('rule_id')
    )

    op.create_table('rule_functions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('rule_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('rule_parameters',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('function_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('condition', sa.String(length=20), nullable=False),
        sa.Column('value', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['function_id'], ['rule_functions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_parameters')
    op.drop_table('rule_functions')
    op.drop_table('rules')
    # ### end Alembic commands ### 